version: '2'

services:
  vreport:
    image: harbor-aio.so.ch/aio/vreport:2.0.5
    container_name: vreport
    restart: always
    expose:
        - "5001"
    environment:
      - VIRTUAL_HOST=vreport.rootso.org
      - CREDENTIALS=${CREDENTIALS}
      - REGISTRY=${REGISTRY}
      - API=${API}
      - CACHE_MAXSIZE=100
    volumes:
      - ./config:/app/config:ro
    networks:
      - frontendproxy_bridge-net

networks:
  frontendproxy_bridge-net:
    external: true
