version: '2'

services:
  vreport:
    image: ${INTERNAL_REGISTRY}/aio/vreport:2.3.1
    container_name: vreport
    restart: always
    ports:
      - "5001:5002"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - CREDENTIALS=${CREDENTIALS}
      - REGISTRY=${REGISTRY}
      - API=${API}
      - PROMETHEUS=${PROMETHEUS}
      - ADMIN_URL=${ADMIN_URL}
      - LOG_LEVEL=${LOG_LEVEL:-warning}
      - CACHE_MAXSIZE=100
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./config:/app/config:ro
#    networks:
#      - frontendproxy_bridge-net
  mongodb:
    image: ${INTERNAL_REGISTRY}/bitnami/mongodb:6.0
    expose:
      - "27017"
    volumes:
      - 'vreport_t:/bitnami/mongodb'

volumes:
  vreport_t:
    driver: local

# networks:
#  frontendproxy_bridge-net:
#    external: true
